### ISSUE TITLE
Hey thank you 

### ISSUE THREAD

**Issue by xentzenith** [MishanPoudel/MishanPoudel#1]
Hey thank you for following me, I followed you back can you just give star last 2 repository which is

https://github.com/xentzenith/x3nos

https://github.com/xentzenith/weather-final-project

I will yours too. Just drop link after starring.

**Comment by xentzenith** [comment]
Btw you gave me inspiration for X3NOS, if you want I can give you credit in app as an Easter Egg in future. And if you have discord I would like to collab with you :)

**Comment by MishanPoudel** [comment]
hey, thank you for your kind words. I've star your both repos and by the way I do have discord, my GitHub user name is "misery6t9". let's collab my friend! :)

**Comment by xentzenith** [comment]
I added my username: x3nraen
